{
 "title": "DurationSeconds",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Duration seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "http_server_request_duration_seconds_count{instance=\"host.docker.internal:5136\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "http_server_request_duration_seconds_count{instance=\"host.docker.internal:5166\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "http_server_request_duration_seconds_count{instance=\"host.docker.internal:5197\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "http_server_active_requests{instance=\"host.docker.internal:5136\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "http_server_active_requests{instance=\"host.docker.internal:5166\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "http_server_active_requests{instance=\"host.docker.internal:5197\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duration seconds bucket",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "http_server_request_duration_seconds_bucket{instance=\"host.docker.internal:5136\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "http_server_request_duration_seconds_bucket{instance=\"host.docker.internal:5166\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "http_server_request_duration_seconds_bucket{instance=\"host.docker.internal:5197\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}